TRUNCATE TABLE reservations RESTART IDENTITY CASCADE;
TRUNCATE TABLE tours RESTART IDENTITY CASCADE;
TRUNCATE TABLE tour_details RESTART IDENTITY CASCADE;
TRUNCATE TABLE tour_operators RESTART IDENTITY CASCADE;
TRUNCATE TABLE clients RESTART IDENTITY CASCADE;
TRUNCATE TABLE users RESTART IDENTITY CASCADE;
TRUNCATE TABLE hotels RESTART IDENTITY CASCADE;
